version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: hp3416431#
    ports:
      - "8051:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
