FROM python:slim

WORKDIR /app

COPY . /app/

RUN pip install -r requirements.txt

RUN python manage.py collectstatic --noinput


CMD ["gunicorn", "--bind", "0.0.0.0:8000", "systemizer.wsgi:application"]

EXPOSE 8000
